# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: my_theme
day_night: false
font: ''
font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email:
phone:
address:
  street: 52 Pritchatts Road
  city: Birmingham
  region: WM
  postcode: 'B15 2TT'
  country: United Kingdom
  country_code: UK
coordinates:
  latitude: '52.452890'
  longitude: '-1.928468'
directions: Enter GK/PR52, take one of the two elevators on the left of the Cafe' to Office 505 
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
appointment_url: ''



# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-gb

# Site features

highlight_superuser : true
highlight: true
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: false
  page: false
  post: false
  project: true
  publication: true
  event: false
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-21178515-2'
  google_tag_manager: 'GTM-MTQ9VJT'
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
